###
get https://www.lego.com


###
post https://www.lego.com/api/graphql/ProductDetailsOverviewQuery
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InB1YiI6e30sInB2dCI6ImhnTy8rbkg0U2EzRXpxdTE0eFhXSVpyTUx2dk5vTEt0L1daQVFWRytJVjAvRVlNTStobnIrcmFOcXVaV296aWtZL3RPQkMwZVF3TGlNdWdsa0dNeU1WUkM3eHBLanV2N01iWjhqNW4zZHNVUW5oK2I0bnNVNVlKeURjL2owdUMyS1REeTNIekZLYkZKZ3ZGejJVNmZLbXBYNXN6TlhZTittUjNUZXBqSXk3bW5WcFB4K3NiWXVnSGdBTkQwL055RmxxS3NxKzRrclJSWkFiV3Y4TytQUUVPaUxQSk5XZWZibzIyZUVNdDdYVnZleFJEZEFWS0VWWDg2UEVWVDBWdTJWUkNzazM1dUVpRzkvY1RPVFdIVWtScFpsTjNkSExXOWQ1ZWZaRUR4MGhyOTNwNTVlWUp4d1pzNFI1Y0FvYkVBUjJxQUwrbXRiYzFqWk5ZbEZQaG9lT3pnYVJBcW5Mb2w1UjNuWkZBVVZkeGZlME04YmZrS29QREQ3a21PdXlqWlFpOE85Tml1MDJ0Y2d6UThQRzJXU1kzMzE1QUNNZndhclIyVitJYkJVV3Y4MjJSZGpmVG9MaWdpTFZTV0JEVFZDUWhYdjdtMHNsanNzU1ZBb0pmTzYra1BveXNVZEozaXNSNnhWUTZWYjF6WmsvOFgvd1o4WFRSZm1tVVRXL25tRTF3SExlL3ZuL0I4L3FXU1R3cnFIR0FrNjVsMEZHdXVPeFlJY3kySG1kMD0uczVJcDR2UitQd291bEI4NENvZmJqUT09In0sImlhdCI6MTU4ODU4ODI0OSwiZXhwIjoxNTg4NzYxMDQ5fQ.r8EFJxBAVGxj7TF0xtz7ebojFzEpn7y2Fv3FPD6qkkE
session_cookie_id: 1ORNy_XP8s59hjflFg3Uf

{
    "operationName": "ProductDetailsOverviewQuery"
    "variables": {
        "productCode": "42100"
    }
}